image:
  # 服务器保存图片的绝对地址
  abs-tmp-path: /root/storage/
  # 图片前缀
  web-img-path: /
  # 临时存储目录
  tmp-upload-path: /tmp/forum/
  # 图片访问域名
  cdn-host: https://techit.asia/
  oss:
    type: local
    endpoint:
    prefix: paicoding/
    ak:
    sk:
    bucket:
    host: https://cdn.tobebetterjavaer.com/
spring:
  web:
      resources:
        # 支持本地图片上传之后的链接，其中 file:///d的用于win系统，后面的file: 适用于mac/linux系统
        static-locations:
          - classpath:/static/
          - file:///d:${image.abs-tmp-path}
          - file:${image.abs-tmp-path}